// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.34.1
// source: tour/tour_service.proto

package tour

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TourService_GetTourPublicInfo_FullMethodName = "/tour.TourService/GetTourPublicInfo"
	TourService_IsTourPublished_FullMethodName   = "/tour.TourService/IsTourPublished"
)

// TourServiceClient is the client API for TourService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TourServiceClient interface {
	GetTourPublicInfo(ctx context.Context, in *GetTourPublicInfoRequest, opts ...grpc.CallOption) (*GetTourPublicInfoResponse, error)
	IsTourPublished(ctx context.Context, in *IsTourPublishedRequest, opts ...grpc.CallOption) (*IsTourPublishedResponse, error)
}

type tourServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTourServiceClient(cc grpc.ClientConnInterface) TourServiceClient {
	return &tourServiceClient{cc}
}

func (c *tourServiceClient) GetTourPublicInfo(ctx context.Context, in *GetTourPublicInfoRequest, opts ...grpc.CallOption) (*GetTourPublicInfoResponse, error) {
	out := new(GetTourPublicInfoResponse)
	err := c.cc.Invoke(ctx, TourService_GetTourPublicInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) IsTourPublished(ctx context.Context, in *IsTourPublishedRequest, opts ...grpc.CallOption) (*IsTourPublishedResponse, error) {
	out := new(IsTourPublishedResponse)
	err := c.cc.Invoke(ctx, TourService_IsTourPublished_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourServiceServer is the server API for TourService service.
// All implementations must embed UnimplementedTourServiceServer
// for forward compatibility
type TourServiceServer interface {
	GetTourPublicInfo(context.Context, *GetTourPublicInfoRequest) (*GetTourPublicInfoResponse, error)
	IsTourPublished(context.Context, *IsTourPublishedRequest) (*IsTourPublishedResponse, error)
	mustEmbedUnimplementedTourServiceServer()
}

// UnimplementedTourServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTourServiceServer struct {
}

func (UnimplementedTourServiceServer) GetTourPublicInfo(context.Context, *GetTourPublicInfoRequest) (*GetTourPublicInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTourPublicInfo not implemented")
}
func (UnimplementedTourServiceServer) IsTourPublished(context.Context, *IsTourPublishedRequest) (*IsTourPublishedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsTourPublished not implemented")
}
func (UnimplementedTourServiceServer) mustEmbedUnimplementedTourServiceServer() {}

// UnsafeTourServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TourServiceServer will
// result in compilation errors.
type UnsafeTourServiceServer interface {
	mustEmbedUnimplementedTourServiceServer()
}

func RegisterTourServiceServer(s grpc.ServiceRegistrar, srv TourServiceServer) {
	s.RegisterService(&TourService_ServiceDesc, srv)
}

func _TourService_GetTourPublicInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTourPublicInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetTourPublicInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_GetTourPublicInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetTourPublicInfo(ctx, req.(*GetTourPublicInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_IsTourPublished_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsTourPublishedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).IsTourPublished(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_IsTourPublished_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).IsTourPublished(ctx, req.(*IsTourPublishedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TourService_ServiceDesc is the grpc.ServiceDesc for TourService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TourService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tour.TourService",
	HandlerType: (*TourServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTourPublicInfo",
			Handler:    _TourService_GetTourPublicInfo_Handler,
		},
		{
			MethodName: "IsTourPublished",
			Handler:    _TourService_IsTourPublished_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tour/tour_service.proto",
}
