// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v7.34.1
// source: tour/tour_service.proto

package tour

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTourPublicInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TourId string `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
}

func (x *GetTourPublicInfoRequest) Reset() {
	*x = GetTourPublicInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_tour_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTourPublicInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourPublicInfoRequest) ProtoMessage() {}

func (x *GetTourPublicInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourPublicInfoRequest.ProtoReflect.Descriptor instead.
func (*GetTourPublicInfoRequest) Descriptor() ([]byte, []int) {
	return file_tour_tour_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetTourPublicInfoRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type GetTourPublicInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TourId      string  `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	Name        string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price       float64 `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *GetTourPublicInfoResponse) Reset() {
	*x = GetTourPublicInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_tour_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTourPublicInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourPublicInfoResponse) ProtoMessage() {}

func (x *GetTourPublicInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourPublicInfoResponse.ProtoReflect.Descriptor instead.
func (*GetTourPublicInfoResponse) Descriptor() ([]byte, []int) {
	return file_tour_tour_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetTourPublicInfoResponse) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *GetTourPublicInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTourPublicInfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetTourPublicInfoResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type IsTourPublishedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TourId string `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
}

func (x *IsTourPublishedRequest) Reset() {
	*x = IsTourPublishedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_tour_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsTourPublishedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsTourPublishedRequest) ProtoMessage() {}

func (x *IsTourPublishedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsTourPublishedRequest.ProtoReflect.Descriptor instead.
func (*IsTourPublishedRequest) Descriptor() ([]byte, []int) {
	return file_tour_tour_service_proto_rawDescGZIP(), []int{2}
}

func (x *IsTourPublishedRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type IsTourPublishedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsPublished bool `protobuf:"varint,1,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
}

func (x *IsTourPublishedResponse) Reset() {
	*x = IsTourPublishedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tour_tour_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsTourPublishedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsTourPublishedResponse) ProtoMessage() {}

func (x *IsTourPublishedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsTourPublishedResponse.ProtoReflect.Descriptor instead.
func (*IsTourPublishedResponse) Descriptor() ([]byte, []int) {
	return file_tour_tour_service_proto_rawDescGZIP(), []int{3}
}

func (x *IsTourPublishedResponse) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

var File_tour_tour_service_proto protoreflect.FileDescriptor

var file_tour_tour_service_proto_rawDesc = []byte{
	0x0a, 0x17, 0x74, 0x6f, 0x75, 0x72, 0x2f, 0x74, 0x6f, 0x75, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x6f, 0x75, 0x72, 0x22,
	0x33, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x75, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74,
	0x6f, 0x75, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f,
	0x75, 0x72, 0x49, 0x64, 0x22, 0x80, 0x01, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x75, 0x72,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x6f, 0x75, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x31, 0x0a, 0x16, 0x49, 0x73, 0x54, 0x6f, 0x75,
	0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x6f, 0x75, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x75, 0x72, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x17, 0x49, 0x73,
	0x54, 0x6f, 0x75, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x32, 0xb3, 0x01, 0x0a, 0x0b, 0x54, 0x6f, 0x75,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x54,
	0x6f, 0x75, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x2e,
	0x74, 0x6f, 0x75, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x75, 0x72, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x74, 0x6f, 0x75, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x75, 0x72, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e,
	0x0a, 0x0f, 0x49, 0x73, 0x54, 0x6f, 0x75, 0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65,
	0x64, 0x12, 0x1c, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x2e, 0x49, 0x73, 0x54, 0x6f, 0x75, 0x72, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x74, 0x6f, 0x75, 0x72, 0x2e, 0x49, 0x73, 0x54, 0x6f, 0x75, 0x72, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1f,
	0x5a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x6f, 0x75, 0x72, 0xaa, 0x02, 0x10, 0x54,
	0x6f, 0x75, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tour_tour_service_proto_rawDescOnce sync.Once
	file_tour_tour_service_proto_rawDescData = file_tour_tour_service_proto_rawDesc
)

func file_tour_tour_service_proto_rawDescGZIP() []byte {
	file_tour_tour_service_proto_rawDescOnce.Do(func() {
		file_tour_tour_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_tour_tour_service_proto_rawDescData)
	})
	return file_tour_tour_service_proto_rawDescData
}

var file_tour_tour_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tour_tour_service_proto_goTypes = []interface{}{
	(*GetTourPublicInfoRequest)(nil),  // 0: tour.GetTourPublicInfoRequest
	(*GetTourPublicInfoResponse)(nil), // 1: tour.GetTourPublicInfoResponse
	(*IsTourPublishedRequest)(nil),    // 2: tour.IsTourPublishedRequest
	(*IsTourPublishedResponse)(nil),   // 3: tour.IsTourPublishedResponse
}
var file_tour_tour_service_proto_depIdxs = []int32{
	0, // 0: tour.TourService.GetTourPublicInfo:input_type -> tour.GetTourPublicInfoRequest
	2, // 1: tour.TourService.IsTourPublished:input_type -> tour.IsTourPublishedRequest
	1, // 2: tour.TourService.GetTourPublicInfo:output_type -> tour.GetTourPublicInfoResponse
	3, // 3: tour.TourService.IsTourPublished:output_type -> tour.IsTourPublishedResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tour_tour_service_proto_init() }
func file_tour_tour_service_proto_init() {
	if File_tour_tour_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tour_tour_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTourPublicInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_tour_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTourPublicInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_tour_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsTourPublishedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tour_tour_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsTourPublishedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tour_tour_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tour_tour_service_proto_goTypes,
		DependencyIndexes: file_tour_tour_service_proto_depIdxs,
		MessageInfos:      file_tour_tour_service_proto_msgTypes,
	}.Build()
	File_tour_tour_service_proto = out.File
	file_tour_tour_service_proto_rawDesc = nil
	file_tour_tour_service_proto_goTypes = nil
	file_tour_tour_service_proto_depIdxs = nil
}
