server {
    listen 8080;

    server_name localhost;

    location = / {
        add_header Content-Type text/plain;
        return 200 "API Gateway is running.\n";
    }

    location = /blog {
        return 301 /blog/;
    }

    location /blog/ {
        proxy_pass http://blog-app:8081/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /stakeholders {
        return 301 /stakeholders/;
    }

    location /stakeholders/ {
        proxy_pass http://stakeholders-app:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
