server {
    listen 8080;

    server_name localhost;

    resolver 127.0.0.11 valid=30s ipv6=off;

    location = / {
        add_header Content-Type text/plain;
        return 200 "API Gateway is running.\n";
    }

    location = /blog {
        return 301 /blog/;
    }

    location /blog/ {
        set $blog http://blog-app:8081;
        rewrite ^/blog/(.*) /$1 break;
        proxy_pass $blog;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /stakeholders {
        return 301 /stakeholders/;
    }

    location /stakeholders/ {
        set $stakeholders http://stakeholders-app:8080;
        rewrite ^/stakeholders/(.*) /$1 break;
        proxy_pass $stakeholders;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /tours {
        return 301 /tours/;
    }

    location /tours/ {
        set $tours http://tour-app:8080;
        rewrite ^/tours/(.*) /$1 break;
        proxy_pass $tours;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /followers/ {
        set $followers http://followers-app:8082;
        rewrite ^/followers/(.*) /$1 break;
        proxy_pass $followers;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
