server.port=8081

spring.data.mongodb.database=${DB_NAME:blog}
spring.data.mongodb.host=${DB_HOST:localhost}
spring.data.mongodb.port=${DB_PORT:27017}
spring.data.mongodb.uuid-representation=standard

spring.data.mongodb.auto-index-creation=true

logging.level.org.springframework=info

followers.grpc.host=${FOLLOWERS_GRPC_HOST:localhost}
followers.grpc.port=${FOLLOWERS_GRPC_PORT:50051}