services:
  app:
    build:
      context: ../
      dockerfile: stakeholders-service/Dockerfile
    container_name: app
    networks:
      - servers
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: disable
      JWT_SECRET: ${JWT_SECRET}
      GRPC_PORT: ${GRPC_PORT}
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:16-alpine
    restart: always
    networks:
      - servers
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

networks:
  servers:
    name: servers
    driver: bridge
