// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: purchase/purchase_service.proto

package purchase

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HasPurchasedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasPurchasedRequest) Reset() {
	*x = HasPurchasedRequest{}
	mi := &file_purchase_purchase_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasPurchasedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPurchasedRequest) ProtoMessage() {}

func (x *HasPurchasedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_purchase_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPurchasedRequest.ProtoReflect.Descriptor instead.
func (*HasPurchasedRequest) Descriptor() ([]byte, []int) {
	return file_purchase_purchase_service_proto_rawDescGZIP(), []int{0}
}

func (x *HasPurchasedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HasPurchasedRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type HasPurchasedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purchased     bool                   `protobuf:"varint,1,opt,name=purchased,proto3" json:"purchased,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasPurchasedResponse) Reset() {
	*x = HasPurchasedResponse{}
	mi := &file_purchase_purchase_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasPurchasedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPurchasedResponse) ProtoMessage() {}

func (x *HasPurchasedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_purchase_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPurchasedResponse.ProtoReflect.Descriptor instead.
func (*HasPurchasedResponse) Descriptor() ([]byte, []int) {
	return file_purchase_purchase_service_proto_rawDescGZIP(), []int{1}
}

func (x *HasPurchasedResponse) GetPurchased() bool {
	if x != nil {
		return x.Purchased
	}
	return false
}

var File_purchase_purchase_service_proto protoreflect.FileDescriptor

const file_purchase_purchase_service_proto_rawDesc = "" +
	"\n" +
	"\x1fpurchase/purchase_service.proto\x12\bpurchase\"G\n" +
	"\x13HasPurchasedRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\"4\n" +
	"\x14HasPurchasedResponse\x12\x1c\n" +
	"\tpurchased\x18\x01 \x01(\bR\tpurchased2`\n" +
	"\x0fPurchaseService\x12M\n" +
	"\fHasPurchased\x12\x1d.purchase.HasPurchasedRequest\x1a\x1e.purchase.HasPurchasedResponseB#Z\x0eproto/purchase\xaa\x02\x10TourService.Grpcb\x06proto3"

var (
	file_purchase_purchase_service_proto_rawDescOnce sync.Once
	file_purchase_purchase_service_proto_rawDescData []byte
)

func file_purchase_purchase_service_proto_rawDescGZIP() []byte {
	file_purchase_purchase_service_proto_rawDescOnce.Do(func() {
		file_purchase_purchase_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_purchase_purchase_service_proto_rawDesc), len(file_purchase_purchase_service_proto_rawDesc)))
	})
	return file_purchase_purchase_service_proto_rawDescData
}

var file_purchase_purchase_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_purchase_purchase_service_proto_goTypes = []any{
	(*HasPurchasedRequest)(nil),  // 0: purchase.HasPurchasedRequest
	(*HasPurchasedResponse)(nil), // 1: purchase.HasPurchasedResponse
}
var file_purchase_purchase_service_proto_depIdxs = []int32{
	0, // 0: purchase.PurchaseService.HasPurchased:input_type -> purchase.HasPurchasedRequest
	1, // 1: purchase.PurchaseService.HasPurchased:output_type -> purchase.HasPurchasedResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_purchase_purchase_service_proto_init() }
func file_purchase_purchase_service_proto_init() {
	if File_purchase_purchase_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_purchase_purchase_service_proto_rawDesc), len(file_purchase_purchase_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_purchase_purchase_service_proto_goTypes,
		DependencyIndexes: file_purchase_purchase_service_proto_depIdxs,
		MessageInfos:      file_purchase_purchase_service_proto_msgTypes,
	}.Build()
	File_purchase_purchase_service_proto = out.File
	file_purchase_purchase_service_proto_goTypes = nil
	file_purchase_purchase_service_proto_depIdxs = nil
}
