services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - servers
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: mongo:7.0.3
    restart: always
    networks:
      - servers
    ports:
      - "27018:27017"
    volumes:
      - blog_mongo_data:/data/db

volumes:
  blog_mongo_data:

networks:
  servers:
    name: servers
    driver: bridge
